apiVersion: v1
kind: Service
metadata: 
  name: name-service
  labels:
    label-key1: label-value1
  annotations:
    annotation-key1: annotations-value1
spec:
  selector:
    label-key1: label-value1
  ports:
    - port: 8080
      targetPort: 80